apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tanladigitalpvt-vaultkubenertes-job
  namespace: tanladigitalpvt-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: tanladigitalpvt-vaultkubenertes-job
  chart:
    git: git@github.com:amitkd-github/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: tanladigitalpvt
      component_type: orderer
      namespace: tanladigitalpvt-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://104.211.212.80:8200/
      authpath: devtanladigitalpvt-net-auth
      policy: vault-crypto-orderer-tanladigitalpvt-net-ro
      secret_path: kv
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://tbs-tan-nld-si-hlf-ord-aks-01-dns-30628a14.hcp.southindia.azmk8s.io:443
